language: perl
perl:
- "5.26"
- "5.24"
- "5.22"
- "5.20"
cache:
  directories:
    -
install:
  - cpanm --installdeps ./code/
  - export PERL5LIB=${PWD}/code/modules
script:
  - perl ./code/scripts/assign_genome_properties.pl -all -gpdir ./flatfiles -gpff genomeProperties.txt -matches testing/testfiles/ecoli_k12_annotation.tsv -outdir ./ -outfiles summary -name ecoli_k12
  - test -s ./SUMMARY_FILE_ecoli_k12
  - find $(perl -E 'say"@INC"') -name CPAN.pm -exec dirname {} \;
notifications:
    email: false